-- RƎ:ALYZE community gallery setup
-- Chạy 1 lần trong Supabase SQL Editor. Script có thể chạy lại.

create table if not exists public.realyze_gallery (
  id bigint generated by default as identity primary key,
  image_url text not null,
  storage_path text not null,
  caption text default '',
  uploader_name text default 'Anonymous',
  created_at timestamptz not null default now()
);

alter table public.realyze_gallery enable row level security;

drop policy if exists "gallery public read" on public.realyze_gallery;
create policy "gallery public read" on public.realyze_gallery for select to anon, authenticated using (true);

drop policy if exists "gallery public insert" on public.realyze_gallery;
create policy "gallery public insert" on public.realyze_gallery for insert to anon, authenticated with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('realyze-gallery','realyze-gallery',true,8388608,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=true, file_size_limit=8388608, allowed_mime_types=array['image/jpeg','image/png','image/webp'];

drop policy if exists "gallery storage public read" on storage.objects;
create policy "gallery storage public read" on storage.objects for select to public using (bucket_id='realyze-gallery');

drop policy if exists "gallery storage public upload" on storage.objects;
create policy "gallery storage public upload" on storage.objects for insert to anon, authenticated with check (bucket_id='realyze-gallery');
